# Generated by Django 5.0.1 on 2024-01-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czujniki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
    ]
