# Generated by Django 5.0.1 on 2024-01-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czujniki', '0002_alter_data_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motion', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'motion',
            },
        ),
    ]
